/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

/**
 *
 * @author GIGABYTE
 */
public class JF_MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form JF_MainMenu
     */
    public JF_MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp_mainmenu = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_registration = new javax.swing.JMenu();
        menu_registration_viewusers = new javax.swing.JMenuItem();
        menu_client = new javax.swing.JMenu();
        menu_client_viewshipping = new javax.swing.JMenuItem();
        menu_cust = new javax.swing.JMenu();
        menu_cust_viewcustomer = new javax.swing.JMenuItem();
        menu_cust_viewshippers = new javax.swing.JMenuItem();
        menu_routes = new javax.swing.JMenu();
        menu_routes_load = new javax.swing.JMenuItem();
        menu_routes_save = new javax.swing.JMenuItem();
        menu_routes_delete = new javax.swing.JMenuItem();
        menu_routes_edit = new javax.swing.JMenuItem();
        menu_routes_viewtablecharge = new javax.swing.JMenuItem();
        menu_freights = new javax.swing.JMenu();
        menu_freights_add = new javax.swing.JMenuItem();
        menu_freights_save = new javax.swing.JMenuItem();
        menu_freights_delete = new javax.swing.JMenuItem();
        menu_freights_edit = new javax.swing.JMenuItem();
        menu_freights_viewbooking = new javax.swing.JMenuItem();
        menu_exit = new javax.swing.JMenu();
        menu_exit_back = new javax.swing.JMenuItem();
        menu_exit_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dp_mainmenuLayout = new javax.swing.GroupLayout(dp_mainmenu);
        dp_mainmenu.setLayout(dp_mainmenuLayout);
        dp_mainmenuLayout.setHorizontalGroup(
            dp_mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1042, Short.MAX_VALUE)
        );
        dp_mainmenuLayout.setVerticalGroup(
            dp_mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menu_registration.setText("Registration");

        menu_registration_viewusers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menu_registration_viewusers.setText("View Users");
        menu_registration_viewusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_registration_viewusersActionPerformed(evt);
            }
        });
        menu_registration.add(menu_registration_viewusers);

        jMenuBar1.add(menu_registration);

        menu_client.setText("Client Management");

        menu_client_viewshipping.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menu_client_viewshipping.setText("View Shipping Companies");
        menu_client.add(menu_client_viewshipping);

        jMenuBar1.add(menu_client);

        menu_cust.setText("Customer Management");

        menu_cust_viewcustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        menu_cust_viewcustomer.setText("View Customer");
        menu_cust.add(menu_cust_viewcustomer);

        menu_cust_viewshippers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.CTRL_MASK));
        menu_cust_viewshippers.setText("View Shippers");
        menu_cust.add(menu_cust_viewshippers);

        jMenuBar1.add(menu_cust);

        menu_routes.setText("Routes Management");

        menu_routes_load.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        menu_routes_load.setText("Load");
        menu_routes.add(menu_routes_load);

        menu_routes_save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_MASK));
        menu_routes_save.setText("Save");
        menu_routes.add(menu_routes_save);

        menu_routes_delete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_MASK));
        menu_routes_delete.setText("Delete");
        menu_routes.add(menu_routes_delete);

        menu_routes_edit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menu_routes_edit.setText("Edit");
        menu_routes.add(menu_routes_edit);

        menu_routes_viewtablecharge.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.ALT_MASK));
        menu_routes_viewtablecharge.setText("View route tables and charges");
        menu_routes.add(menu_routes_viewtablecharge);

        jMenuBar1.add(menu_routes);

        menu_freights.setText("Freights Management");

        menu_freights_add.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_MASK));
        menu_freights_add.setText("Add");
        menu_freights.add(menu_freights_add);

        menu_freights_save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_MASK));
        menu_freights_save.setText("Save");
        menu_freights.add(menu_freights_save);

        menu_freights_delete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_MASK));
        menu_freights_delete.setText("Delete");
        menu_freights.add(menu_freights_delete);

        menu_freights_edit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_MASK));
        menu_freights_edit.setText("Edit");
        menu_freights.add(menu_freights_edit);

        menu_freights_viewbooking.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.SHIFT_MASK));
        menu_freights_viewbooking.setText("View booking freights");
        menu_freights.add(menu_freights_viewbooking);

        jMenuBar1.add(menu_freights);

        menu_exit.setText("Exit");

        menu_exit_back.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0));
        menu_exit_back.setText("Back to Login");
        menu_exit_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_exit_backActionPerformed(evt);
            }
        });
        menu_exit.add(menu_exit_back);

        menu_exit_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_exit_exit.setText("Exit Program");
        menu_exit_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_exit_exitActionPerformed(evt);
            }
        });
        menu_exit.add(menu_exit_exit);

        jMenuBar1.add(menu_exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_mainmenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_mainmenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_exit_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_exit_backActionPerformed
        dispose();
        JF_Login main = new JF_Login();
        main.setVisible(true);
    }//GEN-LAST:event_menu_exit_backActionPerformed

    private void menu_exit_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_exit_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menu_exit_exitActionPerformed

    private void menu_registration_viewusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_registration_viewusersActionPerformed
        JF_Registration register = new JF_Registration();
        dp_mainmenu.add(register);
        register.show();
    }//GEN-LAST:event_menu_registration_viewusersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dp_mainmenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_client;
    private javax.swing.JMenuItem menu_client_viewshipping;
    private javax.swing.JMenu menu_cust;
    private javax.swing.JMenuItem menu_cust_viewcustomer;
    private javax.swing.JMenuItem menu_cust_viewshippers;
    private javax.swing.JMenu menu_exit;
    private javax.swing.JMenuItem menu_exit_back;
    private javax.swing.JMenuItem menu_exit_exit;
    private javax.swing.JMenu menu_freights;
    private javax.swing.JMenuItem menu_freights_add;
    private javax.swing.JMenuItem menu_freights_delete;
    private javax.swing.JMenuItem menu_freights_edit;
    private javax.swing.JMenuItem menu_freights_save;
    private javax.swing.JMenuItem menu_freights_viewbooking;
    private javax.swing.JMenu menu_registration;
    private javax.swing.JMenuItem menu_registration_viewusers;
    private javax.swing.JMenu menu_routes;
    private javax.swing.JMenuItem menu_routes_delete;
    private javax.swing.JMenuItem menu_routes_edit;
    private javax.swing.JMenuItem menu_routes_load;
    private javax.swing.JMenuItem menu_routes_save;
    private javax.swing.JMenuItem menu_routes_viewtablecharge;
    // End of variables declaration//GEN-END:variables
}
